#!/usr/bin/env python3
"""Run reproducible architectural SPICE corners; all text edits write files directly.

Generated decks are deliberately not KiCad-exported transistor-level models.
Reports label assumptions and never equate model acceptance to hardware signoff.
"""
import math
import re
import subprocess
import sys
from pathlib import Path
from build_power import patch_files

ROOT=Path(__file__).resolve().parents[1]

def run(name,base,changes,required):
    text=(ROOT/'simulations'/base).read_text()
    for a,b in changes:
        assert a in text,(name,a)
        text=text.replace(a,b)
    path='simulations/corners/'+name+'.cir'
    patch_files({path:text})
    logfile=ROOT/'simulations/corners'/(name+'.log')
    result=subprocess.run(['ngspice','-b','-o',str(logfile),str(ROOT/path)],capture_output=True,text=True)
    log=logfile.read_text()
    if result.returncode or re.search(r'(?im)(fatal error|error:|.*failed|.*aborted)',log):
        raise RuntimeError(name+'\n'+log)
    measurements={m[0]:float(m[1]) for m in re.findall(r'^([a-z][a-z0-9_]*)\s*=\s*([-+\d.eE]+)',log,re.M)}
    assert all(k in measurements and math.isfinite(measurements[k]) for k in required),(name,measurements)
    return measurements

def run_or_unknown(name,base,changes,required):
    """Like run(), but on a convergence failure retries once with an added
    .options line before giving up; returns (measurements, None) on success
    or (None, exception) after both documented attempts fail."""
    attempts=[changes,changes+[('.options method=gear reltol=0.001',
      '.options method=gear reltol=0.001\n.options gmin=1e-9 itl4=400')]]
    last=None
    for i,c in enumerate(attempts):
        try:
            return run(name if i==0 else name+'_retry',base,c,required),None
        except RuntimeError as e:
            last=e
    return None,last

def main():
    failures=[]
    report=['# MARV V2 power simulation results','',
      'Generated by `python3 tools/run_power_checks.py` with ngspice. These are assumption-based models, not vendor IC simulations or hardware signoff.','',
      '## Integrated source/load model','',
      'Power comes from 5V_IN -- the output of U26, the on-board AP63205WU buck that makes a fixed 5.0 V (4.95/5.00/5.05 V, DS41326 Rev. 2-2) from the 6-25.2 V pack on the ESC pad row J3, modeled as a 5.0 V source behind 0.10 ohm of effective output impedance plus a 2 A hard current limit (the rated continuous output of the part; its high-side peak current limit is 2.5 A min / 2.8 A typ / 3.1 A max), behavioral rather than a vendor regulator model, with the pack and the buck conversion itself outside these decks -- or from USB (J4, a plain 5.0 V rail through 0.35 ohm cable/connector resistance, no current limit -- USB compliance/negotiation is a firmware/operational matter, not modeled here). Both enter ONE U25 TPS2121 priority power mux: IN1 = 5V_IN has priority, IN2 = USB is the fallback, OUT = V5_SYS. It is modeled by the muxctl subckt (the shared selection logic of datasheet Table 9-3 for the CP2 < VREF rows the board uses, with the UV / OV1 / PR1 / VCOMP comparators and their hysteresis) plus one muxpath subckt per channel (RON 56 mOhm typ, tSW 100 us, and always-on reverse-current blocking with IRCB 1 A / tRCB 10 us / VRCB 25 mV and NO body diode -- see the subckt comments and simulations/README.md for what this can and cannot show). V5_SYS bulk capacitance is C8+C9 2 x 10 uF ceramic (14 uF derated in lossy_path) plus C19 220 uF polymer with 40 mOhm ESR (176 uF derated); the 5V_IN node itself now carries 44.1 uF (C76+C77+C71, the AP63205 COUT plus the mux IN1 bypass; the old ~110 uF XT30 input network is gone with the 5 V input) and USB_VBUS ~1.1 uF (C7+C72). U7 TPS62913 (buck, V5_SYS->V3V3_SYS, 92% assumed efficiency, dropout-clamped so VOUT <= VIN-0.15 V) carries the RP2354B digital domains, QSPI flash, microSD and the peripheral ports; U12 TPS7A20 (LDO, V5_SYS->V3V3_ANA, VOUT = min(3.3, VIN-0.2 V), ideal pass-through current) carries the MEMS sensors and the RP2354B ADC_AVDD pin. The nominal corner times 5V_IN present 5-40 ms and USB present 30-55 ms, so each is the sole source for a window (5V_IN alone 5-30 ms, USB alone 40-55 ms) and both overlap 30-40 ms -- and in that overlap the mux now keeps IN1, which is the behaviour the LM66100 pair could not guarantee. Load steps 500->800->500 mA on V3V3_SYS per the budget, with a constant 10 mA on V3V3_ANA. Predicates: V3V3_SYS in the 3.135-3.60 V window and V5_SYS >= 3.5 V whenever a source is present; V3V3_ANA >= 3.135 V. usb_only and vbat_only remove one source for the whole run (the other source\'s own presence window is then the evaluation window); lossy_path adds 50% to both source resistances on top of the derated caps.','',
      '| Corner | V3V3_SYS min | V3V3_SYS max | V3V3_ANA min | V5_SYS min | Model window |',
      '| --- | --- | --- | --- | --- | --- |']
    integrated_required=['vout_min','vout_max','ana_min','vsys_min']
    cases=[('nominal',[]),
      ('lossy_path',[('R5VIN=0.10 RUSB=0.35','R5VIN=0.15 RUSB=0.525'),('CSYS=20u CPOLY=220u','CSYS=14u CPOLY=176u'),('COUT=66u','COUT=52.8u')]),
      ('usb_only',[('PWL(0 0 5m 0 5.1m 5.0 40m 5.0 40.1m 0)','PWL(0 0 5m 0 5.1m 0 40m 0 40.1m 0)'),
        ('TFIRST=5m TMSTART=6.5m TMEND=54.9m','TFIRST=30m TMSTART=31.5m TMEND=54.9m')]),
      ('vbat_only',[('PWL(0 0 30m 0 30.1m 5.0 55m 5.0 55.1m 0)','PWL(0 0 30m 0 30.1m 0 55m 0 55.1m 0)'),
        ('TMEND=54.9m','TMEND=39.9m')])]
    nominal=None
    for name,changes in cases:
        m=run(name,'integrated_power.cir',changes,integrated_required)
        good=(3.135<=m['vout_min']<=m['vout_max']<=3.60) and m['ana_min']>=3.135 and m['vsys_min']>=3.5
        report.append(f"| {name} | {m['vout_min']:.4f} V | {m['vout_max']:.4f} V | {m['ana_min']:.4f} V | {m['vsys_min']:.4f} V | {'within' if good else 'OUTSIDE'} |")
        if not good:
            failures.append(f"integrated {name}: vout_min {m['vout_min']:.4f} V / vout_max {m['vout_max']:.4f} V / ana_min {m['ana_min']:.4f} V / vsys_min {m['vsys_min']:.4f} V")
        if name=='nominal': nominal=m
    loss300=run('loss_300ma','integrated_power.cir',
      [('Iloadsys v3v3sys 0 PWL(0 0 {TFIRST+0.2m} 0 {TFIRST+0.3m} 0.03 {TFIRST+6m} 0.03 {TFIRST+6.01m} {ILO} {TFIRST+11m} {ILO} {TFIRST+11.01m} {IHI} {TFIRST+16m} {IHI} {TFIRST+16.01m} {ILO} 60m {ILO})',
        'Iloadsys v3v3sys 0 PWL(0 0 {TFIRST+0.2m} 0 {TFIRST+0.3m} 0.3 60m 0.3)')],
      ['buck_loss','ldo_loss'])
    ploss300=loss300['buck_loss']+loss300['ldo_loss']
    ploss500=nominal['buck_loss']+nominal['ldo_loss']
    report+=['',f"Modeled converter loss at 500 mA (new nominal continuous load, from the nominal corner's steady 500 mA plateau): buck {nominal['buck_loss']:.3f} W, LDO {nominal['ldo_loss']:.3f} W. At 300 mA (separate constant-load run): buck {loss300['buck_loss']:.3f} W, LDO {loss300['ldo_loss']:.3f} W. These derive from the buck's assumed 92% efficiency and the LDO's ideal pass-through current (Iin=Iout, so its loss is (VIN-VOUT)*IOUT), not device characterization. TPS2121 conduction loss is additional (56 mOhm typ / 100 mOhm max at 125 C, so 20-36 mW at the 0.6 A the mux actually carries).",'']

    report+=['## Source handover, over-voltage and mis-plug with TPS2121 thresholds','',
      'Corners below drive simulations/source_handover.cir directly: a behavioral TPS2121 (datasheet SLVSEA3F -- RON 56 mOhm typ / 100 mOhm max, tSW 100 us for the CP2 < VREF mode the board uses, reverse-current blocking IRCB 1 A typ / 2 A max, tRCB 10 us, VRCB 25 mV typ / 50 mV max, VUV 2.65/2.55 V, VCOMP 280 mV) feeding the same TPS62913-class buck as integrated_power.cir (setpoint 3.33 V, 92% efficiency, vmin 3.0 V, dropout-clamped). There is no cell/battery path; the SURVIVOR (present for the whole run) and the OTHER source (removed, inserted, or held over-voltage at t=15 ms) are 5V_IN and USB, whichever the case assigns, and a third substitutable ROLE block tells the controller which of them is IN1. Both sources sit at their nominal 5.0 V: the LM66100 deck this replaces had to split them 4.6 V / 5.4 V to make the pre-event state well-defined because that part had no priority mechanism, whereas the TPS2121 decides from PR1/OV1/VCOMP, so the split is gone and near-equal sources are now the case actually tested. Two board-derived thresholds carry the OV corners: the OV1 divider R44 45.3k / R45 10k puts the datasheet VREF (1.06 V rising, 1.04 V falling) at 5.862 V / 5.751 V on 5V_IN, and the PR1 divider R42 32.4k / R43 10k puts it at 4.494 V / 4.410 V (centred on the rising edge so the 4.664 V worst-case rising threshold still sits below the 4.75 V minimum declared input). Each channel model has NO body diode -- the TPS2121 is back-to-back FETs with always-on reverse blocking (Sec 9.3.6) -- so the hold-up capacitance, not a forward-biased diode, carries the load across the 100 us switchover; that is strictly harder than the LM66100 case it replaces. The 5V_IN node carries its real 44.1 uF (C76+C77+C71) and USB_VBUS its real ~1.1 uF (C7+C72); that is load-bearing, not cosmetic, because a token 100 nF source cap has too little charge for reverse blocking to separate the rails and the model latches half-on in a state the hardware cannot reach. Each row\'s precondition column reports the state just before the 15 ms event and what it had to be for the row to mean anything: for vin5_removed_usb_present the removed 5V_IN must have been established (>= 4.5 V) and the USB channel must have been held OFF by IN1\'s priority (conduction < 0.1); for usb_removed_vin5_present the surviving 5V_IN channel must have been ON (> 0.9) and the USB channel OFF; for usb_insert_vin5_present and the over-voltage corners the survivor-fed sys rail must already have been running (>= 3.1 V, i.e. buck vmin 3.0 V + margin). Otherwise the row is marked INVALID rather than reporting a meaningless measurement. Every threshold in the state path is a tanh rather than a min/max clamp so the solver never has to step across a discontinuity at the handover instant. This is not a vendor IC simulation: no gate/loop dynamics, no current limiting, no thermal shutdown, no SS-programmed startup slew and no bench measurement are represented. VSYS bulk is 2 x 10 uF ceramic (14 uF derated) plus C19 220 uF polymer (176 uF at -20%) with 40 mOhm ESR. Predicates: V5_SYS >= 3.5 V and V3V3_SYS in the 3.135-3.60 V window, evaluated from 2 ms (well after startup) through the end of the 30 ms run; the two over-voltage corners add V5_SYS <= 5.6 V and IN1 conduction < 0.1 over that whole window.','',
      'The "Other-channel max state" column is the peak conduction fraction of the OTHER source\'s channel over the whole 2-30 ms evaluation window. For vin5_removed_usb_present and the two over-voltage corners the OTHER source is 5V_IN = IN1, so that column is the IN1 rejection evidence (it must stay below 0.1 in the over-voltage corners); for usb_removed_vin5_present and usb_insert_vin5_present the OTHER source is USB = IN2, and 0.000 there means the fallback channel never turned on because IN1 kept priority. A negative reverse peak means even the maximum of the survivor source current is still forward, i.e. no reverse current occurred at any point.','',
      '| Case | Corner | Load | Precondition | VSYS min | VSYS max | V3V3 min | V3V3 max | Other-channel max state | Reverse peak | Reverse duration |',
      '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
    handover_required=['vsys_min','vsys_max','v3v3_min','v3v3_max','rev_peak','rev_dur','src_pre','sys_pre','fet_pre','oth_pre','oth_max']

    # SURVIVOR SOURCE BLOCK variants. USB_SURVIVOR is the on-disk default
    # (present the whole run, plain 0.35 ohm cable resistance -- USB has no
    # current limit -- and its real ~1.1 uF of node capacitance).
    # FIVEVIN_SURVIVOR swaps the series resistance to 5V_IN's 0.10 ohm and the
    # node capacitance to 5V_IN's ~110 uF. The 5V_IN current limiter from
    # integrated_power.cir is deliberately NOT reused in the survivor role:
    # its max(...,0) clamp is a one-way valve (it can source 0-2 A but never
    # sink), and the currents here are far below the 2 A limit regardless.
    USB_SURVIVOR=('Vsrv vsrv0 0 5.0\n'
      'Rsrvres vsrv0 srv {RUSB}\n'
      'Csrvfilt srv 0 1.1u\n'
      'Xsurvivoror srv sys ensrv muxpath params: ron={RONHI} tsw={TSW} trcb={TRCB} ircb={IRCB} vrcb={VRCB}')
    FIVEVIN_SURVIVOR=('Vsrv vsrv0 0 5.0\n'
      'Rsrvres vsrv0 srv {R5VIN}\n'
      'Csrvfilt srv 0 44.1u\n'
      'Xsurvivoror srv sys ensrv muxpath params: ron={RONHI} tsw={TSW} trcb={TRCB} ircb={IRCB} vrcb={VRCB}')
    # OTHER SOURCE BLOCK variants. BEC_REMOVED is the on-disk default (5V_IN
    # present from t=0 at 5.0 V, removed at t=15 ms, current-limited like
    # integrated_power.cir's B5vinlim). BEC_OV65 / BEC_OV84 keep 5V_IN present
    # for the whole run at a voltage above the OV1 trip: a failed U26 partially passing
    # VBAT onto its own output at 6.5 V or 8.4 V. With a fixed 5.00 V +/-1% buck and no 5 V input
    # connector left on the board, a buck failure is the only way 5V_IN can go over-voltage.
    OTHER_TAIL=('Cosrcfilt osrc 0 %s\n'
      'Rosrcbleed osrc 0 100k\n'
      'Xotheror osrc sys enoth muxpath params: ron={RONHI} tsw={TSW} trcb={TRCB} ircb={IRCB} vrcb={VRCB}')
    BEC_LIM='Botherlim vother0 osrc I=min(max(v(vother0,osrc)/R5VIN,0),2.0)\n'
    BEC_REMOVED='Vother vother0 0 PWL(0 5.0 15m 5.0 15.1m 0)\n'+BEC_LIM+OTHER_TAIL%'44.1u'
    USB_REMOVED='Vother vother0 0 PWL(0 5.0 15m 5.0 15.1m 0)\nRotherres vother0 osrc {RUSB}\n'+OTHER_TAIL%'1.1u'
    USB_INSERT='Vother vother0 0 PWL(0 0 15m 0 15.1m 5.0 30m 5.0)\nRotherres vother0 osrc {RUSB}\n'+OTHER_TAIL%'1.1u'
    BEC_OV65='Vother vother0 0 6.5\n'+BEC_LIM+OTHER_TAIL%'44.1u'
    BEC_OV84='Vother vother0 0 8.4\n'+BEC_LIM+OTHER_TAIL%'44.1u'
    # ROLE BLOCK variants: which source the mux controller treats as IN1.
    ROLE_OTHER_IN1='Xmuxctl osrc srv enoth ensrv muxctl params: vuvr={VUVR} vuvf={VUVF} vovr={VOVR} vovf={VOVF} vprr={VPRR} vprf={VPRF} vcmp={VCMP}'
    ROLE_SURVIVOR_IN1='Xmuxctl srv osrc ensrv enoth muxctl params: vuvr={VUVR} vuvf={VUVF} vovr={VOVR} vovf={VOVF} vprr={VPRR} vprf={VPRF} vcmp={VCMP}'
    BEC_SURVIVES=[(USB_SURVIVOR,FIVEVIN_SURVIVOR),(ROLE_OTHER_IN1,ROLE_SURVIVOR_IN1)]

    def handover_row(case,corner_label,corner_slug,load,changes,precondition='src'):
        allchanges=list(changes)
        if abs(load-0.5)>1e-9:
            allchanges=allchanges+[('ILOAD=0.5',f'ILOAD={load}')]
        name=f"{case}_{corner_slug}_{str(load).replace('.','v')}"
        m,err=run_or_unknown(name,'source_handover.cir',allchanges,handover_required)
        if m is None:
            report.append(f"| {case} | {corner_label} | {load:.1f} A |"+' UNKNOWN |'*8)
            print(f'WARNING: {name} did not converge after two documented attempts: {err}')
            return None
        if precondition in ('sys','ov'):
            pre_ok=m['sys_pre']>=3.1
            pre_text=f"sys {m['sys_pre']:.3f} V"
            invalid=f"INVALID (survivor-fed rail never established: {m['sys_pre']:.3f} V)"
        elif precondition=='survivor_on':
            # 5V_IN is the survivor AND holds priority, so its channel must be ON
            # and the USB channel OFF before the USB source is removed.
            srv_on=m['fet_pre']>0.9
            oth_off=m['oth_pre']<0.1
            pre_ok=srv_on and oth_off and m['sys_pre']>=3.1
            pre_text=f"IN1 {'on' if srv_on else 'OFF'} / IN2 {'off' if oth_off else 'ON'}"
            invalid=f"INVALID (pre-event channel states IN1 {m['fet_pre']:.3f} / IN2 {m['oth_pre']:.3f}, sys {m['sys_pre']:.3f} V)"
        else:
            fet_blocked=m['fet_pre']<0.1
            src_ok=m['src_pre']>=4.5
            pre_ok=fet_blocked and src_ok
            pre_text=f"{m['src_pre']:.3f} V / IN2 {'off' if fet_blocked else 'ON'}"
            if not src_ok:
                invalid=f"INVALID (source never established: {m['src_pre']:.3f} V)"
            else:
                invalid=f"INVALID (fallback channel not blocked pre-removal: state {m['fet_pre']:.3f})"
        tail=f"{m['oth_max']:.3f} | {m['rev_peak']:.3f} A | {m['rev_dur']*1000:.4f} ms |"
        if not pre_ok:
            failures.append(f"handover {case}/{corner_slug}/{load}: precondition not met")
            report.append(f"| {case} | {corner_label} | {load:.1f} A | {pre_text} | {invalid} | {invalid} | {invalid} | {invalid} | {tail}")
            return m
        good=m['vsys_min']>=3.5 and 3.135<=m['v3v3_min']<=m['v3v3_max']<=3.60
        if not good:
            failures.append(f"handover {case}/{corner_slug}/{load}: vsys_min {m['vsys_min']:.3f} V / v3v3_min {m['v3v3_min']:.3f} V / v3v3_max {m['v3v3_max']:.3f} V outside predicate")
        if precondition=='ov':
            # IN1 must be rejected by OV1 and V5_SYS must never be dragged up by it.
            if not m['vsys_max']<=5.6:
                failures.append(f"handover {case}/{corner_slug}/{load}: vsys_max {m['vsys_max']:.3f} V exceeds the 5.6 V over-voltage predicate")
            if not m['oth_max']<0.1:
                failures.append(f"handover {case}/{corner_slug}/{load}: IN1 not rejected, channel conduction reached {m['oth_max']:.3f}")
        report.append(f"| {case} | {corner_label} | {load:.1f} A | {pre_text} | {m['vsys_min']:.3f} V | {m['vsys_max']:.3f} V | {m['v3v3_min']:.3f} V | {m['v3v3_max']:.3f} V | {tail}")
        return m

    for load in (0.5,0.8):
        handover_row('vin5_removed_usb_present','typical','typical',load,[])
    for load in (0.5,0.8):
        handover_row('usb_removed_vin5_present','typical','typical',load,BEC_SURVIVES+[(BEC_REMOVED,USB_REMOVED)],precondition='survivor_on')
    for load in (0.5,0.8):
        handover_row('usb_insert_vin5_present','typical','typical',load,BEC_SURVIVES+[(BEC_REMOVED,USB_INSERT)],precondition='sys')
    # New fault corners: 5V_IN held above the OV1 trip for the whole run while USB is present.
    for load in (0.5,0.8):
        handover_row('buck_fault_6v5','typical','typical',load,[(BEC_REMOVED,BEC_OV65)],precondition='ov')
    for load in (0.5,0.8):
        handover_row('buck_fault_8v4','typical','typical',load,[(BEC_REMOVED,BEC_OV84)],precondition='ov')

    # Worst-case device corner: RON at its 125 C maximum, reverse-current detection
    # threshold at its maximum (so more charge moves before blocking completes) and
    # the RCB release voltage at its maximum. tSW has only a typical spec.
    worst_dev=[('RONHI=0.056 TSW=100u TRCB=10u IRCB=1 VRCB=0.025','RONHI=0.100 TSW=100u TRCB=10u IRCB=2 VRCB=0.050')]
    worst_case_changes=worst_dev+[('CSYS=20u CPOLY=220u','CSYS=14u CPOLY=176u')]
    for load in (0.5,0.8):
        handover_row('vin5_removed_usb_present','worst-case (RON=0.100, IRCB=2, VRCB=0.050, CSYS=14u, CPOLY=176u)','worst',load,worst_case_changes)
    for load in (0.5,0.8):
        handover_row('buck_fault_8v4','worst-case (RON=0.100, IRCB=2, VRCB=0.050, CSYS=14u, CPOLY=176u)','worst',load,worst_case_changes+[(BEC_REMOVED,BEC_OV84)],precondition='ov')

    sens=[]
    for csys in ('20u','47u','100u'):
        changes=worst_dev+[('CPOLY=220u','CPOLY=176u')]
        if csys!='20u':
            changes=changes+[('CSYS=20u',f'CSYS={csys}')]
        m,err=run_or_unknown('vin5_removed_usb_present_worst_csys'+csys,'source_handover.cir',changes,handover_required)
        sens.append((csys,None if m is None else m['vsys_min']))
    sens_parts=', '.join(f"{c} = {'UNKNOWN' if v is None else f'{v:.3f} V'}" for c,v in sens)
    keep=[c for c,v in sens if v is not None and v>=3.5]
    keep_text=('CSYS = '+', '.join(keep)+' keep VSYS >= 3.5 V') if keep else 'none of the swept CSYS values keep VSYS >= 3.5 V'
    report+=['',f"Sensitivity: worst-case vin5_removed_usb_present at 0.5 A, VSYS min vs CSYS (polymer term present throughout at its derated CPOLY=176u) -- {sens_parts}; {keep_text}.",'']

    report+=['## Reverse current into the 5V_IN path (TPS2121 reverse-blocking region)','',
      'One corner built from source_handover.cir\'s hooks: USB inserted onto a V5_SYS already running from a present 5V_IN, with no source removal (5V_IN stays present for the whole run), at the worst-case device numbers (RON 100 mOhm, IRCB 2 A, VRCB 50 mV) so the most charge possible moves before reverse blocking completes. This is the corner the LM66100 could not pass by construction -- its reverse current below VOFF was simply not blocked -- whereas the TPS2121 has reverse-current blocking always on for both channels. Reporting-only: no pass/fail predicate is applied.','',
      '| Case | Corner | Load | Reverse current (avg, 20-30 ms) | VSYS (avg, 20-30 ms) | Survivor FET state (avg, 20-30 ms) | Reverse peak | Reverse duration |',
      '| --- | --- | --- | --- | --- | --- | --- | --- |']
    reverse_required=['rev_avg','sys_avg','fet_avg','rev_peak','rev_dur']

    def reverse_row(case,corner_label,load,changes):
        m,err=run_or_unknown(case,'source_handover.cir',changes,reverse_required)
        if m is None:
            report.append(f"| {case} | {corner_label} | {load:.2f} A | UNKNOWN | UNKNOWN | UNKNOWN | UNKNOWN | UNKNOWN |")
            print(f'WARNING: {case} did not converge after two documented attempts: {err}')
            return None
        report.append(f"| {case} | {corner_label} | {load:.2f} A | {m['rev_avg']:.4f} A | {m['sys_avg']:.3f} V | {m['fet_avg']:.3f} | {m['rev_peak']:.3f} A | {m['rev_dur']*1000:.4f} ms |")
        return m

    reverse_row('usb_insert_onto_5vin','worst-case RON=0.100 / IRCB=2 / VRCB=0.050',0.5,
      BEC_SURVIVES+[(BEC_REMOVED,USB_INSERT)]+worst_dev)
    report+=['','A near-zero standing reverse current here is the behaviour the TPS2121 was chosen for: IN1 keeps priority, the IN2 channel never turns on, and neither input can be back-fed from V5_SYS. See DESIGN_SPEC.md.','']

    report+=['','## Enclosure sensitivity — the load also heats the board','',
      f"Assume 60 C surrounding environment and 10 J/K effective board heat capacity. Loss inputs are buck+LDO conversion heat only. 300 mA row: 0.99 W electronics heat (the P3 load budget's typical share) plus {ploss300:.3f} W conversion heat. 500 mA row: 1.3 W onboard electronics heat (external ELRS/GNSS modules dissipate off-board) plus {ploss500:.3f} W conversion heat. Whole-assembly thermal resistance is unknown: the following values are scenarios, not PCB estimates. These temperatures are the lumped board node, not regulator junction temperatures.",'',
      '| Load | Assumed assembly thermal resistance | Board at 10 min | Board at 60 min |',
      '| --- | --- | --- | --- |']
    thermal_scenarios=[('300 mA',[],0.99+ploss300),
      ('500 mA',[('PLOAD=0.99','PLOAD=1.3'),(f'PLOSS=0.11',f'PLOSS={ploss500:.6f}')],1.3+ploss500)]
    for label,tchanges,total in thermal_scenarios:
        for r in [10,20,40]:
            base_changes=tchanges if tchanges else [('PLOSS=0.11',f'PLOSS={ploss300:.6f}')]
            m=run('thermal_'+label.replace(' ','')+'_'+str(r),'enclosure_thermal.cir',base_changes+[('RENC=20',f'RENC={r}')],['board_10min','board_60min'])
            report.append(f"| {label} | {r} K/W | {m['board_10min']:.1f} C | {m['board_60min']:.1f} C |")
            expected=60+total*r
            if not abs(m['board_60min']-expected)<0.1:
                failures.append(f"thermal {label}/{r}K/W: board_60min {m['board_60min']:.1f} C vs expected {expected:.1f} C (self-consistency)")
    report+=['',
      'The weak 40 K/W cooling scenario exceeds the provisional 100 C junction target even at the board node. Low-loss converters alone cannot guarantee acceptable temperature in a sealed enclosure. Measure enclosure coupling, board copper and local regulator gradients; reduce load or add a conductive heat path as needed.','',
      '## Remaining validation','',
      '- Vendor-model or bench checks for regulator loops, startup, current-limit behavior and source handover; the generic models do not cover these.',
      '- USB enumeration/startup/inrush/suspend and higher-current control, including tolerance extremes.',
      '- Real input transients, TVS/fuse coordination and reverse-current pulses.',
      '- Logging and actuator-disturbance tests, and no-airflow enclosure thermal soak.',
      '- Final MPNs, effective capacitance, inductor saturation/temperature and PCB layout.','']
    status_line='Status: PASS' if not failures else f"Status: FAIL — {len(failures)} predicate(s) violated (see rows marked OUTSIDE)"
    report.insert(1,status_line)
    patch_files({'simulations/RESULTS.md':'\n'.join(report)})
    print('\n'.join(report))
    if failures:
        print(f'FAIL: {len(failures)} predicate(s) violated')
        for f in failures:
            print(f)
        sys.exit(1)
    print('PASS')
    sys.exit(0)

if __name__=='__main__': main()
