#!/usr/bin/env python3
"""Run reproducible architectural SPICE corners; all text edits write files directly.

Generated decks are deliberately not KiCad-exported transistor-level models.
Reports label assumptions and never equate model acceptance to hardware signoff.
"""
import math
import re
import subprocess
import sys
from pathlib import Path
from build_power import patch_files

ROOT=Path(__file__).resolve().parents[1]

def run(name,base,changes,required):
    text=(ROOT/'simulations'/base).read_text()
    for a,b in changes:
        assert a in text,(name,a)
        text=text.replace(a,b)
    path='simulations/corners/'+name+'.cir'
    patch_files({path:text})
    logfile=ROOT/'simulations/corners'/(name+'.log')
    result=subprocess.run(['ngspice','-b','-o',str(logfile),str(ROOT/path)],capture_output=True,text=True)
    log=logfile.read_text()
    if result.returncode or re.search(r'(?im)(fatal error|error:|.*failed|.*aborted)',log):
        raise RuntimeError(name+'\n'+log)
    measurements={m[0]:float(m[1]) for m in re.findall(r'^([a-z][a-z0-9_]*)\s*=\s*([-+\d.eE]+)',log,re.M)}
    assert all(k in measurements and math.isfinite(measurements[k]) for k in required),(name,measurements)
    return measurements

def run_or_unknown(name,base,changes,required):
    """Like run(), but on a convergence failure retries once with an added
    .options line before giving up; returns (measurements, None) on success
    or (None, exception) after both documented attempts fail."""
    attempts=[changes,changes+[('.options method=gear reltol=0.001',
      '.options method=gear reltol=0.001\n.options gmin=1e-9 itl4=400')]]
    last=None
    for i,c in enumerate(attempts):
        try:
            return run(name if i==0 else name+'_retry',base,c,required),None
        except RuntimeError as e:
            last=e
    return None,last

def main():
    failures=[]
    report=['# MARV V2 power simulation results','',
      'Generated by `python3 tools/run_power_checks.py` with ngspice. These are assumption-based models, not vendor IC simulations or hardware signoff.','',
      '## Integrated source/load model','',
      'P3 is 5 V-only: no cell/battery path anywhere. Power comes from 5V_IN (J3, an external 2S-6S BEC or 1S BMS/boost module, modeled as 0.10 ohm output impedance plus a 3 A hard current limit, behavioral, not a vendor regulator model) or from USB (J4, a plain 5.0 V rail through 0.35 ohm cable/connector resistance, no current limit -- USB compliance/negotiation is a firmware/operational matter, not modeled here). U3/U5 (LM66100, CE tied to VOUT) OR them onto V5_SYS; each is modeled as the orpath subckt (a hysteretic VON/VOFF comparator plus body diode, not an instantaneous ideal diode -- see orpath comments and simulations/README.md for what this can and cannot show). V5_SYS bulk capacitance is C8+C9 2 x 10 uF ceramic (14 uF derated in lossy_path) plus C19 220 uF polymer with 40 mOhm ESR (176 uF derated). U7 TPS62913 (buck, V5_SYS->V3V3_SYS, 92% assumed efficiency, dropout-clamped so VOUT <= VIN-0.15 V) carries the RP2354B digital domains, QSPI flash, microSD and the peripheral ports; U12 TPS7A20 (LDO, V5_SYS->V3V3_ANA, VOUT = min(3.3, VIN-0.2 V), ideal pass-through current) carries the MEMS sensors and the RP2354B analog pins. The nominal corner times 5V_IN present 5-40 ms and USB present 30-55 ms, so each is the sole source for a window (5V_IN alone 5-30 ms, USB alone 40-55 ms) and both overlap 30-40 ms; load steps 500->800->500 mA on V3V3_SYS per the budget, with a constant 10 mA on V3V3_ANA. Predicates: V3V3_SYS in the 3.135-3.60 V window and V5_SYS >= 3.5 V whenever a source is present; V3V3_ANA >= 3.135 V. usb_only and bec_only remove one source for the whole run (the other source\'s own presence window is then the evaluation window); lossy_path adds 50% to both source resistances on top of the derated caps.','',
      '| Corner | V3V3_SYS min | V3V3_SYS max | V3V3_ANA min | V5_SYS min | Model window |',
      '| --- | --- | --- | --- | --- | --- |']
    integrated_required=['vout_min','vout_max','ana_min','vsys_min']
    cases=[('nominal',[]),
      ('lossy_path',[('R5VIN=0.10 RUSB=0.35','R5VIN=0.15 RUSB=0.525'),('CSYS=20u CPOLY=220u','CSYS=14u CPOLY=176u'),('COUT=66u','COUT=52.8u')]),
      ('usb_only',[('PWL(0 0 5m 0 5.1m 5.0 40m 5.0 40.1m 0)','PWL(0 0 5m 0 5.1m 0 40m 0 40.1m 0)'),
        ('TFIRST=5m TMSTART=6.5m TMEND=54.9m','TFIRST=30m TMSTART=31.5m TMEND=54.9m')]),
      ('bec_only',[('PWL(0 0 30m 0 30.1m 5.0 55m 5.0 55.1m 0)','PWL(0 0 30m 0 30.1m 0 55m 0 55.1m 0)'),
        ('TMEND=54.9m','TMEND=39.9m')])]
    nominal=None
    for name,changes in cases:
        m=run(name,'integrated_power.cir',changes,integrated_required)
        good=(3.135<=m['vout_min']<=m['vout_max']<=3.60) and m['ana_min']>=3.135 and m['vsys_min']>=3.5
        report.append(f"| {name} | {m['vout_min']:.4f} V | {m['vout_max']:.4f} V | {m['ana_min']:.4f} V | {m['vsys_min']:.4f} V | {'within' if good else 'OUTSIDE'} |")
        if not good:
            failures.append(f"integrated {name}: vout_min {m['vout_min']:.4f} V / vout_max {m['vout_max']:.4f} V / ana_min {m['ana_min']:.4f} V / vsys_min {m['vsys_min']:.4f} V")
        if name=='nominal': nominal=m
    loss300=run('loss_300ma','integrated_power.cir',
      [('Iloadsys v3v3sys 0 PWL(0 0 {TFIRST+0.2m} 0 {TFIRST+0.3m} 0.03 {TFIRST+6m} 0.03 {TFIRST+6.01m} {ILO} {TFIRST+11m} {ILO} {TFIRST+11.01m} {IHI} {TFIRST+16m} {IHI} {TFIRST+16.01m} {ILO} 60m {ILO})',
        'Iloadsys v3v3sys 0 PWL(0 0 {TFIRST+0.2m} 0 {TFIRST+0.3m} 0.3 60m 0.3)')],
      ['buck_loss','ldo_loss'])
    ploss300=loss300['buck_loss']+loss300['ldo_loss']
    ploss500=nominal['buck_loss']+nominal['ldo_loss']
    report+=['',f"Modeled converter loss at 500 mA (new nominal continuous load, from the nominal corner's steady 500 mA plateau): buck {nominal['buck_loss']:.3f} W, LDO {nominal['ldo_loss']:.3f} W. At 300 mA (separate constant-load run): buck {loss300['buck_loss']:.3f} W, LDO {loss300['ldo_loss']:.3f} W. These derive from the buck's assumed 92% efficiency and the LDO's ideal pass-through current (Iin=Iout, so its loss is (VIN-VOUT)*IOUT), not device characterization. LM66100 conduction/OR-path losses are additional.",'']

    report+=['## Source handover with LM66100 thresholds','',
      'Corners below drive simulations/source_handover.cir directly: a behavioral LM66100 comparator (datasheet SLVSEZ8A limits VON 80-250 mV, VOFF 0-80 mV, tON 40 us, tOFF 2 us, body-diode VFWD 0.5-1.1 V) feeding the same TPS62913-class buck as integrated_power.cir (setpoint 3.33 V, 92% efficiency, vmin 3.0 V, dropout-clamped). There is no cell/battery path; the SURVIVOR (present for the whole run) and the OTHER source (removed or inserted at t=15 ms) are 5V_IN and USB, whichever the case assigns; both use the LM66100\'s ~110 mOhm RON figure for ~5 V sources. Because P3\'s two sources are both nominally 5 V and DESIGN_SPEC notes that near-equal sources share rather than one cleanly dominating, the SURVIVOR is held at 4.6 V and the OTHER at 5.4 V (a plausible tolerance stack-up, not a designed hierarchy) so the pre-event state is well-defined; this split was verified by trace inspection to release the losing FET cleanly even at worst-case VON/VOFF/VFWD and 0.8 A load -- a smaller split leaves the OR-ed node differential inside the worst-case VOFF band and the FET sticks on. Each row\'s "Pre-removal source / survivor blocked" column reports the removed rail (or, for usb_insert_bec_present, the survivor-fed V5_SYS) measured just before the 15 ms handover event, plus -- for the removed-source cases -- whether the survivor\'s orpath had actually blocked (conduction fraction < 0.1) by then; if the source was never established (< 4.5 V) or the survivor path never blocked, or (insert case) the survivor-fed sys rail was never established (< 3.1 V, i.e. buck vmin 3.0 V + margin), the row is marked INVALID rather than reporting a meaningless handover measurement. Turn-on is a dead band rather than a time constant: an internal timer ramps linearly 0 to 1 over tON while the forward condition holds (and resets within tOFF if it does not), the channel stays fully off until the timer is ~90% expired and then ramps to full RON over the last ~10% -- about 36 us of body-diode-only conduction followed by a ~4 us ramp at tON = 40 us -- with each threshold written as a tanh rather than a min/max clamp so the solver never has to step across a discontinuity at the handover instant. This is not a vendor IC simulation: no gate/loop dynamics and no bench measurement are represented. VSYS bulk is 2 x 10 uF ceramic (14 uF derated) plus C19 220 uF polymer (176 uF at -20%) with 40 mOhm ESR. Predicates: V5_SYS >= 3.5 V and V3V3_SYS in the 3.135-3.60 V window, evaluated from 2 ms (well after startup) through the end of the 30 ms run.','',
      '| Case | Corner | Load | Pre-removal source / survivor blocked | VSYS min | V3V3 min | V3V3 max | Reverse peak | Reverse duration |',
      '| --- | --- | --- | --- | --- | --- | --- | --- | --- |']
    handover_required=['vsys_min','v3v3_min','v3v3_max','rev_peak','rev_dur','src_pre','sys_pre','fet_pre']

    # SURVIVOR SOURCE BLOCK variants. USB_SURVIVOR is the on-disk default
    # (present the whole run, plain 0.35 ohm cable resistance -- USB has no
    # current limit). FIVEVIN_SURVIVOR swaps only the series resistance to
    # 5V_IN's 0.10 ohm; the 5V_IN current limiter from integrated_power.cir
    # is deliberately NOT reused here -- its max(...,0) clamp is a one-way
    # valve (it can source 0-3 A but never sink), and when 5V_IN plays the
    # BLOCKED role, the model needs the node to be pulled back down once the
    # other source wins the initial startup race, or the losing FET never
    # releases (verified by trace inspection). A plain resistor gives that
    # bidirectional path; the currents here are far below the 3 A limit
    # regardless, so the limiter would have been a no-op if it had worked.
    USB_SURVIVOR=('Vsrv vsrv0 0 4.6\n'
      'Rsrvres vsrv0 srv {RUSB}\n'
      'Xsurvivoror srv sys orpath params: von={VON} voff={VOFF} vfwd={VFWD} tond={TON} toffd={TOFF} ron={RONHI} ircb={IRCB}')
    FIVEVIN_SURVIVOR=('Vsrv vsrv0 0 4.6\n'
      'Rsrvres vsrv0 srv {R5VIN}\n'
      'Xsurvivoror srv sys orpath params: von={VON} voff={VOFF} vfwd={VFWD} tond={TON} toffd={TOFF} ron={RONHI} ircb={IRCB}')
    # OTHER SOURCE BLOCK variants. BEC_REMOVED is the on-disk default
    # (5V_IN present from t=0 at 5.4 V, removed at t=15 ms, current-limited
    # like integrated_power.cir's B5vinlim -- safe here because 5V_IN is
    # always the dominant/forward-conducting role in this block).
    BEC_REMOVED=('Vother vother0 0 PWL(0 5.4 15m 5.4 15.1m 0)\n'
      'Botherlim vother0 osrc I=min(max(v(vother0,osrc)/R5VIN,0),3.0)\n'
      'Cosrcfilt osrc 0 100n\n'
      'Rosrcbleed osrc 0 100k\n'
      'Xotheror osrc sys orpath params: von={VON} voff={VOFF} vfwd={VFWD} tond={TON} toffd={TOFF} ron={RONHI} ircb={IRCB}')
    USB_REMOVED=('Vother vother0 0 PWL(0 5.4 15m 5.4 15.1m 0)\n'
      'Rotherres vother0 osrc {RUSB}\n'
      'Cosrcfilt osrc 0 100n\n'
      'Rosrcbleed osrc 0 100k\n'
      'Xotheror osrc sys orpath params: von={VON} voff={VOFF} vfwd={VFWD} tond={TON} toffd={TOFF} ron={RONHI} ircb={IRCB}')
    USB_INSERT=('Vother vother0 0 PWL(0 0 15m 0 15.1m 5.4 30m 5.4)\n'
      'Rotherres vother0 osrc {RUSB}\n'
      'Cosrcfilt osrc 0 100n\n'
      'Rosrcbleed osrc 0 100k\n'
      'Xotheror osrc sys orpath params: von={VON} voff={VOFF} vfwd={VFWD} tond={TON} toffd={TOFF} ron={RONHI} ircb={IRCB}')

    def handover_row(case,corner_label,corner_slug,load,changes,precondition='src'):
        allchanges=list(changes)
        if abs(load-0.5)>1e-9:
            allchanges=allchanges+[('ILOAD=0.5',f'ILOAD={load}')]
        name=f"{case}_{corner_slug}_{str(load).replace('.','v')}"
        m,err=run_or_unknown(name,'source_handover.cir',allchanges,handover_required)
        if m is None:
            report.append(f"| {case} | {corner_label} | {load:.1f} A | UNKNOWN | UNKNOWN | UNKNOWN | UNKNOWN | UNKNOWN | UNKNOWN |")
            print(f'WARNING: {name} did not converge after two documented attempts: {err}')
            return None
        if precondition=='sys':
            pre_ok=m['sys_pre']>=3.1
            pre_text=f"{m['sys_pre']:.3f} V"
            invalid=f"INVALID (source never established: {m['sys_pre']:.3f} V)"
        else:
            fet_blocked=m['fet_pre']<0.1
            src_ok=m['src_pre']>=4.5
            pre_ok=fet_blocked and src_ok
            pre_text=f"{m['src_pre']:.3f} V / {'yes' if fet_blocked else 'no'}"
            if not src_ok:
                invalid=f"INVALID (source never established: {m['src_pre']:.3f} V)"
            else:
                invalid=f"INVALID (survivor path not blocked pre-removal: state {m['fet_pre']:.3f})"
        if not pre_ok:
            failures.append(f"handover {case}/{corner_slug}/{load}: precondition not met")
            report.append(f"| {case} | {corner_label} | {load:.1f} A | {pre_text} | {invalid} | {invalid} | {invalid} | {m['rev_peak']:.3f} A | {m['rev_dur']*1000:.4f} ms |")
            return m
        good=m['vsys_min']>=3.5 and 3.135<=m['v3v3_min']<=m['v3v3_max']<=3.60
        if not good:
            failures.append(f"handover {case}/{corner_slug}/{load}: vsys_min {m['vsys_min']:.3f} V / v3v3_min {m['v3v3_min']:.3f} V / v3v3_max {m['v3v3_max']:.3f} V outside predicate")
        report.append(f"| {case} | {corner_label} | {load:.1f} A | {pre_text} | {m['vsys_min']:.3f} V | {m['v3v3_min']:.3f} V | {m['v3v3_max']:.3f} V | {m['rev_peak']:.3f} A | {m['rev_dur']*1000:.4f} ms |")
        return m

    for load in (0.5,0.8):
        handover_row('bec_removed_usb_present','typical','typical',load,[])
    for load in (0.5,0.8):
        handover_row('usb_removed_bec_present','typical','typical',load,[(USB_SURVIVOR,FIVEVIN_SURVIVOR),(BEC_REMOVED,USB_REMOVED)])
    for load in (0.5,0.8):
        handover_row('usb_insert_bec_present','typical','typical',load,[(USB_SURVIVOR,FIVEVIN_SURVIVOR),(BEC_REMOVED,USB_INSERT)],precondition='sys')

    worst_von=[('VON=0.150 VOFF=0.035 VFWD=0.5','VON=0.250 VOFF=0.080 VFWD=1.1')]
    worst_case_changes=worst_von+[('CSYS=20u CPOLY=220u','CSYS=14u CPOLY=176u')]
    for load in (0.5,0.8):
        handover_row('bec_removed_usb_present','worst-case (VON=0.250 VOFF=0.080 VFWD=1.1, CSYS=14u, CPOLY=176u)','worst',load,worst_case_changes)

    sens=[]
    for csys in ('20u','47u','100u'):
        changes=worst_von+[('CPOLY=220u','CPOLY=176u')]
        if csys!='20u':
            changes=changes+[('CSYS=20u',f'CSYS={csys}')]
        m,err=run_or_unknown('bec_removed_usb_present_worst_csys'+csys,'source_handover.cir',changes,handover_required)
        sens.append((csys,None if m is None else m['vsys_min']))
    sens_parts=', '.join(f"{c} = {'UNKNOWN' if v is None else f'{v:.3f} V'}" for c,v in sens)
    keep=[c for c,v in sens if v is not None and v>=3.5]
    keep_text=('CSYS = '+', '.join(keep)+' keep VSYS >= 3.5 V') if keep else 'none of the swept CSYS values keep VSYS >= 3.5 V'
    report+=['',f"Sensitivity: worst-case bec_removed_usb_present at 0.5 A, VSYS min vs CSYS (polymer term present throughout at its derated CPOLY=176u) -- {sens_parts}; {keep_text}.",'']

    report+=['## Reverse current into the 5V_IN path (LM66100 sub-VOFF region)','',
      'One corner built from source_handover.cir\'s hooks: USB inserted (worst-case VOFF=0.080 V) onto a V5_SYS already running from a present 5V_IN, with no source removal (5V_IN stays present for the whole run). Reporting-only: no pass/fail predicate is applied.','',
      '| Case | Corner | Load | Reverse current (avg, 20-30 ms) | VSYS (avg, 20-30 ms) | Survivor FET state (avg, 20-30 ms) | Reverse peak | Reverse duration |',
      '| --- | --- | --- | --- | --- | --- | --- | --- |']
    reverse_required=['rev_avg','sys_avg','fet_avg','rev_peak','rev_dur']

    def reverse_row(case,corner_label,load,changes):
        m,err=run_or_unknown(case,'source_handover.cir',changes,reverse_required)
        if m is None:
            report.append(f"| {case} | {corner_label} | {load:.2f} A | UNKNOWN | UNKNOWN | UNKNOWN | UNKNOWN | UNKNOWN |")
            print(f'WARNING: {case} did not converge after two documented attempts: {err}')
            return None
        report.append(f"| {case} | {corner_label} | {load:.2f} A | {m['rev_avg']:.4f} A | {m['sys_avg']:.3f} V | {m['fet_avg']:.3f} | {m['rev_peak']:.3f} A | {m['rev_dur']*1000:.4f} ms |")
        return m

    reverse_row('usb_insert_onto_5vin','worst-case VOFF=0.080',0.5,
      [(USB_SURVIVOR,FIVEVIN_SURVIVOR),(BEC_REMOVED,USB_INSERT),('VOFF=0.035','VOFF=0.080')])
    report+=['','This quantifies the LM66100 property that reverse current below VOFF/RON is not blocked; see DESIGN_SPEC.md.','']

    report+=['','## Enclosure sensitivity — the load also heats the board','',
      f"Assume 60 C surrounding environment and 10 J/K effective board heat capacity. Loss inputs are buck+LDO conversion heat only. 300 mA row: 0.99 W electronics heat (the P3 load budget's typical share) plus {ploss300:.3f} W conversion heat. 500 mA row: 1.3 W onboard electronics heat (external ELRS/GNSS modules dissipate off-board) plus {ploss500:.3f} W conversion heat. Whole-assembly thermal resistance is unknown: the following values are scenarios, not PCB estimates. These temperatures are the lumped board node, not regulator junction temperatures.",'',
      '| Load | Assumed assembly thermal resistance | Board at 10 min | Board at 60 min |',
      '| --- | --- | --- | --- |']
    thermal_scenarios=[('300 mA',[],0.99+ploss300),
      ('500 mA',[('PLOAD=0.99','PLOAD=1.3'),(f'PLOSS=0.11',f'PLOSS={ploss500:.6f}')],1.3+ploss500)]
    for label,tchanges,total in thermal_scenarios:
        for r in [10,20,40]:
            base_changes=tchanges if tchanges else [('PLOSS=0.11',f'PLOSS={ploss300:.6f}')]
            m=run('thermal_'+label.replace(' ','')+'_'+str(r),'enclosure_thermal.cir',base_changes+[('RENC=20',f'RENC={r}')],['board_10min','board_60min'])
            report.append(f"| {label} | {r} K/W | {m['board_10min']:.1f} C | {m['board_60min']:.1f} C |")
            expected=60+total*r
            if not abs(m['board_60min']-expected)<0.1:
                failures.append(f"thermal {label}/{r}K/W: board_60min {m['board_60min']:.1f} C vs expected {expected:.1f} C (self-consistency)")
    report+=['',
      'The weak 40 K/W cooling scenario exceeds the provisional 100 C junction target even at the board node. Low-loss converters alone cannot guarantee acceptable temperature in a sealed enclosure. Measure enclosure coupling, board copper and local regulator gradients; reduce load or add a conductive heat path as needed.','',
      '## Remaining validation','',
      '- Vendor-model or bench checks for regulator loops, startup, current-limit behavior and source handover; the generic models do not cover these.',
      '- USB enumeration/startup/inrush/suspend and higher-current control, including tolerance extremes.',
      '- Real input transients, TVS/fuse coordination and reverse-current pulses.',
      '- Logging and actuator-disturbance tests, and no-airflow enclosure thermal soak.',
      '- Final MPNs, effective capacitance, inductor saturation/temperature and PCB layout.','']
    status_line='Status: PASS' if not failures else f"Status: FAIL — {len(failures)} predicate(s) violated (see rows marked OUTSIDE)"
    report.insert(1,status_line)
    patch_files({'simulations/RESULTS.md':'\n'.join(report)})
    print('\n'.join(report))
    if failures:
        print(f'FAIL: {len(failures)} predicate(s) violated')
        for f in failures:
            print(f)
        sys.exit(1)
    print('PASS')
    sys.exit(0)

if __name__=='__main__': main()
